import OpenDistillationFactory.Materials.Elasticity.FCC
import OpenDistillationFactory.Materials.Distillation.Operator
import OpenDistillationFactory.Materials.Distillation.ScalarBulkOperator
import OpenDistillationFactory.Materials.Distillation.DirectionalCorrectionScheme
import OpenDistillationFactory.Materials.Distillation.Extracted
import OpenDistillationFactory.Materials.Mechanics.HallPetch
import OpenDistillationFactory.Materials.Scope.Validity

-- Data layer: provenance, benchmark entries, embedded datasets
import OpenDistillationFactory.Materials.Data.Provenance
import OpenDistillationFactory.Materials.Data.Benchmark
import OpenDistillationFactory.Materials.Data.EmpiricalParadox

-- Analysis layer: statistics, causal inference, and manifold geometry
import OpenDistillationFactory.Materials.Analysis.Stats
import OpenDistillationFactory.Materials.Analysis.Causal
import OpenDistillationFactory.Materials.Analysis.Manifold

-- Computation layer: reproducible simulation traces
import OpenDistillationFactory.Materials.Computation.LammpsTrace

-- Theory layer: first-principles conjectures and bounds
import OpenDistillationFactory.Materials.Theory.ParameterBound
import OpenDistillationFactory.Materials.Theory.MetaScience
import OpenDistillationFactory.Materials.Theory.HyperRibbon
import OpenDistillationFactory.Materials.Theory.HyperRibbonEmpirical
import OpenDistillationFactory.Materials.Theory.RibbonProjection
import OpenDistillationFactory.Materials.Theory.ExactTubularUniversality
import OpenDistillationFactory.Materials.Theory.ContextSpecificProof
import OpenDistillationFactory.Materials.Theory.AccuracyCommitment
import OpenDistillationFactory.Materials.Theory.UniversalityBridge
import OpenDistillationFactory.Materials.Theory.ProjectedRibbon
import OpenDistillationFactory.Materials.Theory.ErrorGeometry
import OpenDistillationFactory.Materials.Theory.ProjectionLaw
import OpenDistillationFactory.Materials.Theory.SpectrumBridge
import OpenDistillationFactory.Materials.Theory.ConvexProjection
import OpenDistillationFactory.Materials.Theory.WeakAcceleration

-- Climate-series physics layer: the environment error field and the
-- defect-kinetics laws for the five material classes (LMR cathodes, halide
-- electrolytes, MOF DAC sorbents, ammonia catalysts, lead-free perovskites)
import OpenDistillationFactory.Materials.Theory.EnvironmentField
import OpenDistillationFactory.Materials.Theory.BarrierArrhenius
import OpenDistillationFactory.Materials.Theory.RankingIntegrity
import OpenDistillationFactory.Materials.Theory.ScalingVolcano
import OpenDistillationFactory.Materials.Theory.DefectStability
import OpenDistillationFactory.Materials.Theory.SorptionStability
import OpenDistillationFactory.Materials.Theory.AnchoredField

-- Measured per-cell fields bound from the Y-matrix corpus (generated by
-- python/scripts/bind_env_field_instances.py)
import OpenDistillationFactory.Materials.DistillAtlas.EnvFieldInstances
-- QUARANTINED 2026-07-02: AlloyResidualTransfer does not compile (unknown
-- constants Submodule.finrank / structure-field mismatches) and has broken
-- main's lake build since the 2026-06-28 sync push. Re-import once repaired.
-- import OpenDistillationFactory.Materials.Theory.AlloyResidualTransfer

-- Validation layer: experiment design, integrity checks, and audit
import OpenDistillationFactory.Materials.Validation.Experiment
import OpenDistillationFactory.Materials.Validation.Audit
import OpenDistillationFactory.Materials.Validation.ClimateSeries

-- Executable vision: the build-locking epistemic contract
import OpenDistillationFactory.Materials.Vision
