"""Tier-1 statics physics core: structures, EOS, lattice, defects, surfaces.

Calculator-agnostic (any ASE calculator), deterministic, and fail-fast. Every
public compute function returns a frozen result dataclass with
``canonical_inputs()`` (deterministic, JSON-serializable run identity) and
``to_dict()`` (uniform property/values/units/canonical_inputs envelope).
"""

from __future__ import annotations

from lupine_distill.statics.alloys import (
    RSS_STRUCTURE_TYPES,
    build_rss_supercell,
    estimate_rss_lattice_constant,
    site_counts_for_supercell,
)
from lupine_distill.statics.calculations import (
    DEFAULT_FMAX,
    DEFAULT_MAX_RECENTER,
    DEFAULT_MAX_STEPS,
    DEFAULT_N_POINTS,
    DEFAULT_OPTIMIZER,
    DEFAULT_SUPERCELL,
    DEFAULT_VOLUME_SPAN,
    EosResult,
    FormationEnthalpyResult,
    LatticeResult,
    VacancyFormationResult,
    compute_eos,
    compute_formation_enthalpy,
    compute_lattice,
    compute_vacancy_formation,
)
from lupine_distill.statics.defects import (
    ReferencedVacancyFormationResult,
    SchottkyFormationResult,
    compute_referenced_vacancy_formation,
    compute_schottky_formation,
)
from lupine_distill.statics.elastic import (
    DEFAULT_STRAIN_DELTA,
    VOIGT_CONVENTION,
    CubicElasticResult,
    compute_cubic_elastic_constants,
    validate_strain_delta,
)
from lupine_distill.statics.eos import (
    BirchMurnaghanFit,
    fit_birch_murnaghan,
    scan_energy_volume,
    validate_scan_parameters,
)
from lupine_distill.statics.gates import (
    BORN_PROVENANCE,
    DEFAULT_DISPERSION_FLOOR_FRACTION,
    DISPERSION_METRIC_FLOORED_V1,
    DYNAMIC_RETURN_LIMITS,
    PROPERTY_EVIDENCE_NAMES,
    ConcordanceThresholds,
    GateVerdict,
    born_stability_cubic,
    concordance,
    derive_concordance_thresholds,
    derive_per_property_thresholds,
    dispersions_by_material,
    dispersions_by_material_floored,
    dynamic_return,
    facet_ordering,
    load_property_by_material,
    relative_dispersion,
)
from lupine_distill.statics.errors import (
    CalculationError,
    ConvergenceError,
    InputValidationError,
    StaticsError,
)
from lupine_distill.statics.licenses import (
    LICENSES_SCHEMA_ID,
    LICENSE_STATUSES,
    STATUS_ANTI_CORRELATED,
    STATUS_DESCRIPTIVE,
    STATUS_LICENSED,
    GateLicense,
    LicenseRegistry,
    annotate_concordance,
    derive_status,
    driving_license_summary,
    license_for,
    license_registry_block,
    load_license_registry,
    registry_program_note,
)
from lupine_distill.statics.migration import (
    DEFAULT_N_IMAGES,
    DEFAULT_NEB_FMAX,
    DEFAULT_NEB_MAX_STEPS,
    SUPPORTED_NEB_OPTIMIZERS,
    MigrationBarrierResult,
    build_cation_vacancy_hop,
    build_fcc_vacancy_hop,
    compute_migration_barrier,
    endpoint_band_minimum_check,
)
from lupine_distill.statics.relax import (
    SUPPORTED_OPTIMIZERS,
    relax_positions,
    single_point_energy,
    validate_relax_parameters,
)
from lupine_distill.statics.structures import (
    SUPPORTED_STRUCTURE_TYPES,
    build_structure,
    estimate_lattice_constant,
    normalize_structure_type,
    parse_formula,
    validate_lattice_constant,
)
from lupine_distill.statics.surfaces import (
    SFE_METHOD,
    SUPPORTED_SURFACES,
    StackingFaultResult,
    SurfaceEnergyResult,
    compute_stacking_fault_energy,
    compute_surface_energies,
    compute_surface_energy,
)

__all__ = [
    "BORN_PROVENANCE",
    "BirchMurnaghanFit",
    "CalculationError",
    "ConcordanceThresholds",
    "ConvergenceError",
    "CubicElasticResult",
    "DEFAULT_DISPERSION_FLOOR_FRACTION",
    "DEFAULT_FMAX",
    "DEFAULT_STRAIN_DELTA",
    "DISPERSION_METRIC_FLOORED_V1",
    "DYNAMIC_RETURN_LIMITS",
    "GateVerdict",
    "DEFAULT_MAX_RECENTER",
    "DEFAULT_MAX_STEPS",
    "DEFAULT_N_IMAGES",
    "DEFAULT_NEB_FMAX",
    "DEFAULT_NEB_MAX_STEPS",
    "DEFAULT_N_POINTS",
    "DEFAULT_OPTIMIZER",
    "DEFAULT_SUPERCELL",
    "DEFAULT_VOLUME_SPAN",
    "EosResult",
    "FormationEnthalpyResult",
    "GateLicense",
    "InputValidationError",
    "LICENSES_SCHEMA_ID",
    "LICENSE_STATUSES",
    "LatticeResult",
    "LicenseRegistry",
    "MigrationBarrierResult",
    "PROPERTY_EVIDENCE_NAMES",
    "STATUS_ANTI_CORRELATED",
    "STATUS_DESCRIPTIVE",
    "STATUS_LICENSED",
    "RSS_STRUCTURE_TYPES",
    "ReferencedVacancyFormationResult",
    "SFE_METHOD",
    "SUPPORTED_NEB_OPTIMIZERS",
    "SUPPORTED_OPTIMIZERS",
    "SUPPORTED_STRUCTURE_TYPES",
    "SUPPORTED_SURFACES",
    "SchottkyFormationResult",
    "StackingFaultResult",
    "StaticsError",
    "SurfaceEnergyResult",
    "VOIGT_CONVENTION",
    "VacancyFormationResult",
    "annotate_concordance",
    "born_stability_cubic",
    "build_cation_vacancy_hop",
    "build_fcc_vacancy_hop",
    "build_rss_supercell",
    "build_structure",
    "compute_cubic_elastic_constants",
    "compute_eos",
    "compute_formation_enthalpy",
    "compute_lattice",
    "compute_migration_barrier",
    "compute_referenced_vacancy_formation",
    "compute_schottky_formation",
    "compute_stacking_fault_energy",
    "compute_surface_energies",
    "compute_surface_energy",
    "compute_vacancy_formation",
    "concordance",
    "derive_concordance_thresholds",
    "derive_per_property_thresholds",
    "derive_status",
    "dispersions_by_material",
    "dispersions_by_material_floored",
    "driving_license_summary",
    "dynamic_return",
    "endpoint_band_minimum_check",
    "estimate_lattice_constant",
    "estimate_rss_lattice_constant",
    "facet_ordering",
    "fit_birch_murnaghan",
    "license_for",
    "license_registry_block",
    "load_license_registry",
    "load_property_by_material",
    "normalize_structure_type",
    "parse_formula",
    "registry_program_note",
    "relative_dispersion",
    "relax_positions",
    "scan_energy_volume",
    "single_point_energy",
    "site_counts_for_supercell",
    "validate_lattice_constant",
    "validate_relax_parameters",
    "validate_scan_parameters",
    "validate_strain_delta",
]
