#!/usr/bin/env node
/**
 * Compile src/registry/prompts/<Class>.<variant>.md into a single committed
 * TS module (src/registry/prompts.gen.ts) that the Worker bundle can import.
 *
 * The Worker is a plain `wrangler deploy` esbuild bundle — it cannot read
 * .md files at runtime. The Evolver (evals/evolver.ts) writes new
 * <Class>.<variant>.md files + bumps active.json; the deploy workflow runs
 * THIS script before `wrangler deploy` so those edits land in the bundle.
 * Keep the generated file committed too, so a plain local build works
 * without running the script first.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const promptsDir = join(here, "..", "src", "registry", "prompts");
const outFile = join(here, "..", "src", "registry", "prompts.gen.ts");

const files = readdirSync(promptsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const entries = files.map((f) => {
  const key = f.replace(/\.md$/, ""); // "<Class>.<variant>"
  const text = readFileSync(join(promptsDir, f), "utf8");
  return `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`;
});

const banner =
  "// AUTO-GENERATED by scripts/gen-prompts.mjs — do not edit by hand.\n" +
  "// Source of truth: src/registry/prompts/<Class>.<variant>.md\n" +
  "// Regenerated in CI before `wrangler deploy`.\n\n";

writeFileSync(
  outFile,
  `${banner}export const PROMPTS: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
);

console.log(`gen-prompts: wrote ${files.length} prompt(s) → src/registry/prompts.gen.ts`);
