//! Elastic constant calculation via LAMMPS box deformation.
//!
//! Generates LAMMPS input scripts that compute C11, C12, C44 for cubic
//! crystals (FCC or BCC) using the standard small-strain perturbation method:
//!
//! 1. Create crystal, minimize energy
//! 2. Apply small uniaxial strain ±δ in x, measure σ_xx → C11, σ_yy → C12
//! 3. Apply small shear strain ±δ in xy, measure σ_xy → C44
//!
//! The strain magnitude δ = 1e-6 is small enough for linear response
//! but large enough for numerical stability.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use crate::mlip_ops::{MlipDeployment, MlipOpsError};

/// Crystal structure type.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum LatticeType {
    Fcc,
    Bcc,
}

impl LatticeType {
    pub fn as_lammps_str(&self) -> &'static str {
        match self {
            LatticeType::Fcc => "fcc",
            LatticeType::Bcc => "bcc",
        }
    }
}

/// Configuration for an elastic constant calculation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ElasticCalcConfig {
    /// Element symbol, e.g. "Al"
    pub element: String,
    /// Crystal structure
    pub lattice_type: LatticeType,
    /// Lattice constant in Angstroms
    pub lattice_constant: f64,
    /// Strain magnitude for finite differences
    pub strain_delta: f64,
    /// NIST potential implementation ID (for provenance)
    pub nist_id: String,
}

impl ElasticCalcConfig {
    /// Create a config for a known benchmark metal.
    pub fn for_element(element: &str, nist_id: &str) -> Option<Self> {
        let (lattice_type, a0) = lattice_data(element)?;
        Some(Self {
            element: element.to_string(),
            lattice_type,
            lattice_constant: a0,
            strain_delta: 1e-6,
            nist_id: nist_id.to_string(),
        })
    }
}

/// Returns (LatticeType, lattice_constant_angstroms) for benchmark metals.
///
/// Lattice constants from Kittel, "Introduction to Solid State Physics" (8th ed.)
/// at room temperature.
pub fn lattice_data(element: &str) -> Option<(LatticeType, f64)> {
    match element {
        // FCC metals
        "Al" => Some((LatticeType::Fcc, 4.05)),
        "Cu" => Some((LatticeType::Fcc, 3.615)),
        "Ni" => Some((LatticeType::Fcc, 3.524)),
        "Ag" => Some((LatticeType::Fcc, 4.085)),
        "Au" => Some((LatticeType::Fcc, 4.078)),
        "Pt" => Some((LatticeType::Fcc, 3.924)),
        "Pd" => Some((LatticeType::Fcc, 3.89)),
        "Pb" => Some((LatticeType::Fcc, 4.95)),
        // BCC metals
        "Fe" => Some((LatticeType::Bcc, 2.87)),
        "Cr" => Some((LatticeType::Bcc, 2.91)),
        "Mo" => Some((LatticeType::Bcc, 3.147)),
        "W" => Some((LatticeType::Bcc, 3.165)),
        "V" => Some((LatticeType::Bcc, 3.03)),
        "Nb" => Some((LatticeType::Bcc, 3.30)),
        "Ta" => Some((LatticeType::Bcc, 3.30)),
        _ => None,
    }
}

/// Generate the complete LAMMPS input script for elastic constant calculation.
///
/// The script uses the energy-based stress-strain method:
/// - Minimizes the crystal
/// - Applies +/- strain perturbations
/// - Computes elastic constants from finite differences of the stress tensor
///
/// Results are printed as `ELASTIC_C11`, `ELASTIC_C12`, `ELASTIC_C44` lines
/// in the LAMMPS log, parseable by `parse_elastic_output`.
pub fn generate_elastic_script(
    config: &ElasticCalcConfig,
    deployment: &MlipDeployment,
) -> Result<String, MlipOpsError> {
    // Build the type map for pair_coeff generation
    let mut type_map = BTreeMap::new();
    type_map.insert(1, config.element.clone());
    let pair_block = deployment.construct_pair_style(&type_map)?;

    let lattice_cmd = config.lattice_type.as_lammps_str();
    let a0 = config.lattice_constant;
    let delta = config.strain_delta;

    // The script uses LAMMPS variables and the change_box command to apply
    // small strains and measure the stress response.
    let script = format!(
        r#"# ══════════════════════════════════════════════════════════════
# Elastic Constant Calculation: {element} ({lattice})
# NIST ID: {nist_id}
# Method: Stress-strain finite differences (delta = {delta:.1e})
# Generated by lupine-ops
# ══════════════════════════════════════════════════════════════

units metal
boundary p p p
atom_style atomic

# ── Crystal Setup ──
lattice {lattice} {a0}
region box block 0 5 0 5 0 5
create_box 1 box
create_atoms 1 box
mass 1 1.0

# ── Potential ──
{pair_block}

# ── Variables ──
variable delta equal {delta}
variable len0 equal lx

# ── Initial Minimization ──
thermo 100
min_style cg
minimize 1e-25 1e-25 50000 100000

# Store equilibrium state
variable tmp equal pxx
variable pxx0 equal ${{tmp}}
variable tmp equal pyy
variable pyy0 equal ${{tmp}}
variable tmp equal pzz
variable pzz0 equal ${{tmp}}
variable tmp equal pxy
variable pxy0 equal ${{tmp}}
variable tmp equal lx
variable lx0 equal ${{tmp}}
variable tmp equal ly
variable ly0 equal ${{tmp}}
variable tmp equal lz
variable lz0 equal ${{tmp}}

# ══════════════════════════════════════════════════════════════
# Uniaxial strain in x → C11, C12
# ══════════════════════════════════════════════════════════════

# Positive x strain
variable delta_lx equal ${{lx0}}*${{delta}}
change_box all x delta 0 ${{delta_lx}} remap units box
minimize 1e-25 1e-25 50000 100000
variable tmp equal pxx
variable pxx_pos equal ${{tmp}}
variable tmp equal pyy
variable pyy_pos equal ${{tmp}}

# Reset
change_box all x final 0 ${{lx0}} remap units box
minimize 1e-25 1e-25 50000 100000

# Negative x strain
change_box all x delta 0 -${{delta_lx}} remap units box
minimize 1e-25 1e-25 50000 100000
variable tmp equal pxx
variable pxx_neg equal ${{tmp}}
variable tmp equal pyy
variable pyy_neg equal ${{tmp}}

# Reset
change_box all x final 0 ${{lx0}} remap units box
minimize 1e-25 1e-25 50000 100000

# C11 = -(d sigma_xx / d epsilon_xx)
# In LAMMPS, pressure is negative stress, so C11 = -(pxx_pos - pxx_neg)/(2*delta)
# Convert from bar to GPa: 1 bar = 1e-4 GPa. LAMMPS metal units: pressure in bars.
variable C11 equal -(v_pxx_pos-v_pxx_neg)/(2*v_delta)/10000
variable C12 equal -(v_pyy_pos-v_pyy_neg)/(2*v_delta)/10000

# ══════════════════════════════════════════════════════════════
# Shear strain xy → C44
# ══════════════════════════════════════════════════════════════

change_box all triclinic

# Positive xy tilt
variable delta_xy equal ${{ly0}}*${{delta}}
change_box all xy delta ${{delta_xy}} remap units box
minimize 1e-25 1e-25 50000 100000
variable tmp equal pxy
variable pxy_pos equal ${{tmp}}

# Reset
change_box all xy final 0.0 remap units box
minimize 1e-25 1e-25 50000 100000

# Negative xy tilt
change_box all xy delta -${{delta_xy}} remap units box
minimize 1e-25 1e-25 50000 100000
variable tmp equal pxy
variable pxy_neg equal ${{tmp}}

# Reset
change_box all xy final 0.0 remap units box

# C44 = -(d sigma_xy / d epsilon_xy)
variable C44 equal -(v_pxy_pos-v_pxy_neg)/(2*v_delta)/10000

# ══════════════════════════════════════════════════════════════
# Output — these lines are parsed by lupine-ops
# ══════════════════════════════════════════════════════════════

print "ELASTIC_C11 = ${{C11}}"
print "ELASTIC_C12 = ${{C12}}"
print "ELASTIC_C44 = ${{C44}}"
print "ELASTIC_ELEMENT = {element}"
print "ELASTIC_NIST_ID = {nist_id}"
print "ELASTIC_DONE"
"#,
        element = config.element,
        lattice = lattice_cmd,
        nist_id = config.nist_id,
        delta = delta,
        a0 = a0,
        pair_block = pair_block,
    );

    Ok(script)
}

/// Parsed elastic constant results from LAMMPS output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ElasticResult {
    pub element: String,
    pub nist_id: String,
    pub c11: f64,
    pub c12: f64,
    pub c44: f64,
    /// Whether the calculation completed successfully
    pub converged: bool,
}

impl ElasticResult {
    /// Voigt-Reuss-Hill bulk modulus: K = (C11 + 2*C12) / 3
    pub fn bulk_modulus(&self) -> f64 {
        (self.c11 + 2.0 * self.c12) / 3.0
    }

    /// Voigt shear modulus: G = (C11 - C12 + 3*C44) / 5
    pub fn shear_modulus(&self) -> f64 {
        (self.c11 - self.c12 + 3.0 * self.c44) / 5.0
    }

    /// Zener anisotropy ratio: A = 2*C44 / (C11 - C12)
    pub fn zener_ratio(&self) -> f64 {
        if (self.c11 - self.c12).abs() < 1e-10 {
            f64::NAN
        } else {
            2.0 * self.c44 / (self.c11 - self.c12)
        }
    }

    /// Quick physical sanity check on the elastic constants.
    /// For a stable cubic crystal: C11 > 0, C44 > 0, C11 > |C12|,
    /// (C11 + 2*C12) > 0, (C11 - C12) > 0
    pub fn is_physically_reasonable(&self) -> bool {
        self.c11 > 0.0
            && self.c44 > 0.0
            && self.c11 > self.c12.abs()
            && (self.c11 + 2.0 * self.c12) > 0.0
            && (self.c11 - self.c12) > 0.0
    }
}

/// Parse LAMMPS log output to extract elastic constants.
///
/// Looks for the sentinel lines:
/// ```text
/// ELASTIC_C11 = 107.3
/// ELASTIC_C12 = 60.8
/// ELASTIC_C44 = 28.1
/// ELASTIC_ELEMENT = Al
/// ELASTIC_NIST_ID = 1999--Mishin-Y--Al--LAMMPS--ipr1
/// ELASTIC_DONE
/// ```
pub fn parse_elastic_output(log_text: &str) -> Option<ElasticResult> {
    let mut c11: Option<f64> = None;
    let mut c12: Option<f64> = None;
    let mut c44: Option<f64> = None;
    let mut element = String::new();
    let mut nist_id = String::new();
    let mut done = false;

    for line in log_text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("ELASTIC_C11 = ") {
            c11 = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("ELASTIC_C12 = ") {
            c12 = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("ELASTIC_C44 = ") {
            c44 = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("ELASTIC_ELEMENT = ") {
            element = rest.trim().to_string();
        } else if let Some(rest) = line.strip_prefix("ELASTIC_NIST_ID = ") {
            nist_id = rest.trim().to_string();
        } else if line == "ELASTIC_DONE" {
            done = true;
        }
    }

    if done {
        Some(ElasticResult {
            element,
            nist_id,
            c11: c11.unwrap_or(f64::NAN),
            c12: c12.unwrap_or(f64::NAN),
            c44: c44.unwrap_or(f64::NAN),
            converged: c11.is_some() && c12.is_some() && c44.is_some(),
        })
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mlip_ops::MlipBackend;

    #[test]
    fn test_lattice_data_coverage() {
        let fcc = ["Al", "Cu", "Ni", "Ag", "Au", "Pt", "Pd", "Pb"];
        let bcc = ["Fe", "Cr", "Mo", "W", "V", "Nb", "Ta"];

        for &el in &fcc {
            let (lt, a0) = lattice_data(el).unwrap();
            assert_eq!(lt, LatticeType::Fcc);
            assert!(a0 > 2.0 && a0 < 6.0, "Unreasonable a0 for {}: {}", el, a0);
        }

        for &el in &bcc {
            let (lt, a0) = lattice_data(el).unwrap();
            assert_eq!(lt, LatticeType::Bcc);
            assert!(a0 > 2.0 && a0 < 4.0, "Unreasonable a0 for {}: {}", el, a0);
        }
    }

    #[test]
    fn test_elastic_script_generation() {
        let config = ElasticCalcConfig::for_element("Al", "test--Al--LAMMPS--ipr1").unwrap();
        let deployment =
            MlipDeployment::new(MlipBackend::EamAlloy, "test").with_path("/path/to/Al.eam.alloy");
        let script = generate_elastic_script(&config, &deployment).unwrap();

        assert!(script.contains("lattice fcc 4.05"));
        assert!(script.contains("pair_style eam/alloy"));
        assert!(script.contains("ELASTIC_C11"));
        assert!(script.contains("ELASTIC_DONE"));
    }

    #[test]
    fn test_parse_elastic_output() {
        let log = r#"
Some LAMMPS output here
ELASTIC_C11 = 107.3
ELASTIC_C12 = 60.8
ELASTIC_C44 = 28.1
ELASTIC_ELEMENT = Al
ELASTIC_NIST_ID = 1999--Mishin-Y--Al--LAMMPS--ipr1
ELASTIC_DONE
"#;
        let result = parse_elastic_output(log).unwrap();
        assert!((result.c11 - 107.3).abs() < 0.01);
        assert!((result.c12 - 60.8).abs() < 0.01);
        assert!((result.c44 - 28.1).abs() < 0.01);
        assert_eq!(result.element, "Al");
        assert!(result.converged);
        assert!(result.is_physically_reasonable());
    }

    #[test]
    fn test_elastic_result_derived_quantities() {
        let r = ElasticResult {
            element: "Al".to_string(),
            nist_id: "test".to_string(),
            c11: 108.2,
            c12: 61.3,
            c44: 28.5,
            converged: true,
        };
        // K = (108.2 + 2*61.3) / 3 = 76.93
        assert!((r.bulk_modulus() - 76.93).abs() < 0.1);
        // G = (108.2 - 61.3 + 3*28.5) / 5 = 26.48
        assert!((r.shear_modulus() - 26.48).abs() < 0.1);
        // A = 2*28.5 / (108.2 - 61.3) = 1.215
        assert!((r.zener_ratio() - 1.215).abs() < 0.01);
    }

    #[test]
    fn test_incomplete_output() {
        let log = "ELASTIC_C11 = 100.0\nSome noise\n";
        assert!(
            parse_elastic_output(log).is_none(),
            "Should return None without ELASTIC_DONE"
        );
    }
}
