//! Static property calculation (Lattice Constant and Cohesive Energy).
//!
//! Generates LAMMPS input scripts that compute `a0` and `E_coh` for cubic crystals:
//!
//! 1. Create crystal with approximate lattice constant
//! 2. Relax the box size and atomic positions (fix box/relax)
//! 3. Measure equilibrium box length and total potential energy
//! 4. Compute a0 = L / N_cells and E_coh = PE / N_atoms

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use crate::elastic::LatticeType;
use crate::mlip_ops::{MlipDeployment, MlipOpsError};

/// Configuration for a static property calculation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaticsCalcConfig {
    /// Element symbol, e.g. "Al"
    pub element: String,
    /// Crystal structure
    pub lattice_type: LatticeType,
    /// Initial guess for lattice constant in Angstroms
    pub lattice_constant_guess: f64,
    /// NIST potential implementation ID (for provenance)
    pub nist_id: String,
}

impl StaticsCalcConfig {
    /// Create a config for a known benchmark metal using data from elastic module.
    pub fn for_element(element: &str, nist_id: &str) -> Option<Self> {
        let (lattice_type, a0_guess) = crate::elastic::lattice_data(element)?;
        Some(Self {
            element: element.to_string(),
            lattice_type,
            lattice_constant_guess: a0_guess,
            nist_id: nist_id.to_string(),
        })
    }
}

/// Generate the complete LAMMPS input script for statics calculation.
pub fn generate_statics_script(
    config: &StaticsCalcConfig,
    deployment: &MlipDeployment,
) -> Result<String, MlipOpsError> {
    // Build the type map for pair_coeff generation
    let mut type_map = BTreeMap::new();
    type_map.insert(1, config.element.clone());
    let pair_block = deployment.construct_pair_style(&type_map)?;

    let lattice_cmd = config.lattice_type.as_lammps_str();
    let a0 = config.lattice_constant_guess;

    let script = format!(
        r#"# ══════════════════════════════════════════════════════════════
# Statics Calculation: {element} ({lattice})
# NIST ID: {nist_id}
# Method: Zero-pressure box relaxation
# Generated by lupine-ops
# ══════════════════════════════════════════════════════════════

units metal
boundary p p p
atom_style atomic

# ── Crystal Setup ──
lattice {lattice} {a0}
region box block 0 5 0 5 0 5
create_box 1 box
create_atoms 1 box
mass 1 1.0

# ── Potential ──
{pair_block}

# ── Minimization ──
thermo 10
thermo_style custom step pe lx ly lz press pxx pyy pzz
min_style cg

# Relax both atomic positions and box dimensions (iso 0.0 bar)
fix 1 all box/relax iso 0.0 vmax 0.001
minimize 1e-25 1e-25 50000 100000
unfix 1

# ── Measurements ──
variable num_atoms equal count(all)
# We created a 5x5x5 supercell, so a0 = lx / 5
variable a0 equal lx/5.0
# Cohesive energy is potential energy per atom
variable ecoh equal pe/v_num_atoms

# ══════════════════════════════════════════════════════════════
# Output — these lines are parsed by lupine-ops
# ══════════════════════════════════════════════════════════════

print "STATICS_A0 = ${{a0}}"
print "STATICS_ECOH = ${{ecoh}}"
print "STATICS_ELEMENT = {element}"
print "STATICS_NIST_ID = {nist_id}"
print "STATICS_DONE"
"#,
        element = config.element,
        lattice = lattice_cmd,
        nist_id = config.nist_id,
        a0 = a0,
        pair_block = pair_block,
    );

    Ok(script)
}

/// Parsed static results from LAMMPS output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaticsResult {
    pub element: String,
    pub nist_id: String,
    pub a0: f64,
    pub ecoh: f64,
    /// Whether the calculation completed successfully
    pub converged: bool,
}

impl StaticsResult {
    /// Quick physical sanity check on the statics.
    /// a0 should be positive and reasonable (e.g. 2 to 6 Angstroms for metals).
    /// Ecoh should be negative (bound state).
    pub fn is_physically_reasonable(&self) -> bool {
        self.a0 > 1.0 && self.a0 < 10.0 && self.ecoh < 0.0
    }
}

/// Parse LAMMPS log output to extract statics.
pub fn parse_statics_output(log_text: &str) -> Option<StaticsResult> {
    let mut a0: Option<f64> = None;
    let mut ecoh: Option<f64> = None;
    let mut element = String::new();
    let mut nist_id = String::new();
    let mut done = false;

    for line in log_text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("STATICS_A0 = ") {
            a0 = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("STATICS_ECOH = ") {
            ecoh = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("STATICS_ELEMENT = ") {
            element = rest.trim().to_string();
        } else if let Some(rest) = line.strip_prefix("STATICS_NIST_ID = ") {
            nist_id = rest.trim().to_string();
        } else if line == "STATICS_DONE" {
            done = true;
        }
    }

    if done {
        Some(StaticsResult {
            element,
            nist_id,
            a0: a0.unwrap_or(f64::NAN),
            ecoh: ecoh.unwrap_or(f64::NAN),
            converged: a0.is_some() && ecoh.is_some(),
        })
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mlip_ops::MlipBackend;

    #[test]
    fn test_statics_script_generation() {
        let config = StaticsCalcConfig::for_element("Al", "test--Al--LAMMPS--ipr1").unwrap();
        let deployment =
            MlipDeployment::new(MlipBackend::EamAlloy, "test").with_path("/path/to/Al.eam.alloy");
        let script = generate_statics_script(&config, &deployment).unwrap();

        assert!(script.contains("lattice fcc 4.05"));
        assert!(script.contains("pair_style eam/alloy"));
        assert!(script.contains("fix 1 all box/relax iso 0.0 vmax 0.001"));
        assert!(script.contains("STATICS_A0"));
        assert!(script.contains("STATICS_DONE"));
    }

    #[test]
    fn test_parse_statics_output() {
        let log = r#"
Some LAMMPS output here
STATICS_A0 = 4.049
STATICS_ECOH = -3.360
STATICS_ELEMENT = Al
STATICS_NIST_ID = 1999--Mishin-Y--Al--LAMMPS--ipr1
STATICS_DONE
"#;
        let result = parse_statics_output(log).unwrap();
        assert!((result.a0 - 4.049).abs() < 0.001);
        assert!((result.ecoh - -3.360).abs() < 0.001);
        assert_eq!(result.element, "Al");
        assert!(result.converged);
        assert!(result.is_physically_reasonable());
    }
}
